### PR TITLE
U-Boot: 2021.10 → 2022.07

### PR DESCRIPTION
**Pull request by samueldr**
Let's finish what I started a small while ago

### TODO

 - [x] Check `XXX` commits
 - [x] Build all devices
 - [x] Test enough representative devices
     - [x] pine64-pinebookA64 (mmcboot installer from blank)
     - [x] pine64-pinebookPro (SPI installer from blank)
     - [x] pine64-rockpro64 [@psstoyanov / @PureTryOut]
     - [x] pine64-pinephoneA64 [@psstoyanov / @PureTryOut]
     - [x] pine64-pinephonePro [@PureTryOut]
     - [x] odroid-C4 [@tpwrules]
     - [x] odroid-N2 [@tpwrules]
     - [x] orangePi-pc
     - [x] pine64-pineA64LTS
     - [x] radxa-zero2
     - [x] libreComputer-rocRk3399PcMezzanine
     - [x] libreComputer-amlS805xAc
     - [x] raspberryPi-aarch64

 

 - *Systems I can't test*
     - [x] radxa-RockPi4 (**rk3399 was spicy this upgrade cycle, might require testing**)
     - [x] radxa-RockPi4C (**same**)
     - [ ] odroid-C2 (Likely fine)
     - [x] pine64-pineA64 (Allwinner is generally boring, should be good)
     - [x] olimex-teresI (Allwinner is generally boring, should be good)
     - [x] orangePi-zeroPlus2H5 (Allwinner is generally boring, should be good)

 - [x] Remove "markers" from commit history

NOTE: systems I can't test are generally covered enough by my representative set of devices. It probably won't be an issue not to test them.

* * *

### Issues noticed

 - [x] ~~upstream regression with rk8xx~~
     - [x] ~~causing regression with USB support with at least the Pinebook Pro~~
 - [x] ~~OS Boot order might be broken again for some scenarios~~
     - [x] ~~Pinebook A64 wouldn't launch installer from installer media startup...~~
     - [x] ~~Pinebook Pro lists SD before eMMC in the boot menu...~~

#### `radxa-zero2`

The mmc/sd device order was previously broken in the initial device enablement in `2021.10-005`. This is a Tow-Boot issue, not an upstream issue, nor a vendor issue.

To upgrade Tow-Boot **from 2021.10** to any further version, first use a 2021.10 `mmcboot` installer, then use the erase function. Once erased, boot the system from SD with the `*-006` or following release of Tow-Boot and install.

Since the install base of the `radxa-zero2` users using Tow-Boot is likely limited to a really limited number of units, this is a low priority breakage.

### CODE REVIEW

**Comment by samueldr** [comment]
Most recent push fixed *build* for the few leftover devices that didn't build.

Still untested on most devices. Will test later.

**Comment by tpwrules** [comment]
Features tested and working on `odroid-C4`:
* HDMI output
* USB keyboard input
* Serial (via official system console header) input and output
* SD and eMMC install
* SD and eMMC extlinux NixOS boot
* DHCP IP acquisition

UEFI USB booting still does not work very well (SD/eMMC not detected). I wonder if I need to poke upstream about the device trees. I figured they would be synced by now but maybe there is a differing assumption somewhere.

**Comment by tpwrules** [comment]
Features tested and working on `odroid-N2` (plus):
* HDMI output
* USB keyboard input
* Serial (via official system console header) input and output
* Install to SPI from SD
* SD and eMMC install and extlinux NixOS boot
* SD and eMMC extlinux NixOS boot running on SPI
* DHCP IP acquisition
* UEFI USB NixOS ISO boot

**Comment by PureTryOut** [comment]
Tested on a RockPro64, PinePhone Pro and PinePhone, all installed to either SPI or eMMC boot partitions.. Installation works fine, booting works fine. On the RockPro64 it actually fixed https://github.com/Tow-Boot/Tow-Boot/issues/186 for me (that issue probably shouldn't have been closed till this PR has been merged) which is awesome.

Good to go on those devices!

**Comment by psstoyanov** [comment]
Tested with RockPro64 with TowBoot installed on the SPI:
-> USB keyboard can be used to navigate TowBoot
Systems used to boot:
-> Manjaro ARM
-> RCade v 1.0.7: https://github.com/retro-center/rcade_releases/releases/tag/1.0.7

RCade is a bit unstable at the moment but I'm not sure if that is because of the interaction between RCade's BSP kernel or something else.
Will spend a bit more time with Manjaro tomorrow on this board.

Scheduled for the next couple of days:
- Pinebook Pro
- PinePhone (A64)

**Comment by samueldr** [comment]
> RCade is a bit unstable at the moment but I'm not sure if that is because of the interaction between RCade's BSP kernel or something else.

One thing to consider is building stock U-Boot at 2022.07 for the board and compare. If it is just as unstable (which I would kinda expect) it means it's not Tow-Boot specific

**Comment by psstoyanov** [comment]
I would expect the same but that test would be for later. The instability is odd though - I get it consistently with a few movies in Kodi in RCade but not with others.

Anyway, PBP and PinePhone will be next.

**Comment by psstoyanov** [comment]
I didn't have success with Pinebook Pro and `2022.07`

After flashing to the SPI, I couldn't use the keyboard to navigate either TowBoot nor Fedora Workstation's Grub menu.
I can't observe the same behaviour with `2021.10`

Tow-Boot `2022.07` sha256sum of the `spi.installer.img` that can't use the keyboard to navigate:
`a318f0cc77c85700c495868419b7259ac44428a95cb1de8da35f3f509b6be971`

This is in full contrast to what I experienced with RP64 where the USB keyboard works as intended.


If someone else can confirm the same behaviour on the PinebookPro, it will be great. I've retested a couple of times but a double-check would be better

**Update:**
Using the binaries generated with `2022.07` on the PBP instead of the image.
The disk image generation may not be byte-reproduceable at this point of time as @samueldr noted

<details>
<summary> Binaries with 2022.07 sha256sum </summary>

```shell-session
$ sha256sum *
8ea8d8905f8068be983ec41909b4e401ae529c3a8e34cb9ae2532615b8238194  Tow-Boot.noenv.bin
599a3bf7bc4b7a5e19af5da804e502528bead6ccce9181010dd4603a90c5a2f2  Tow-Boot.spi.bin
```

</details>

**Comment by shvetsnikita** [comment]
`odroid-N2`
It works for me too. Fedora 37 and Debian 12 was tested and works.

`odroid-c4`
Fedora 37 boot fine (I didn't tested Debian 12) but only from USB drive. Neither eMMC nor microSD is detected (Tow-Boot is flashed to microSD) - I not sure if it's Linux 5.19 or Tow-Boot issue. On a side note, maximum resolution is 1920x1080 instead of native 2560x1600 (hardware support up to 4K),

`roc-rk3399-pc`
USB doesn't work at all now (there is no such issue with Tow-Boot 2021.10-005) and #183 is still reproducible.

**Comment by Strit** [comment]
> Using the binaries generated with `2022.07` on the PBP instead of the image.

Did this work @psstoyanov or still no keyboard/USB?

**Comment by psstoyanov** [comment]
> > Using the binaries generated with `2022.07` on the PBP instead of the image.
> 
> Did this work @psstoyanov or still no keyboard/USB?

I haven't checked for USB on the Pinebook Pro. After the integrated kb didn't work, I didn't proceed further with testing.

Uart *definitely* required before testing ⚠️ 

I can try it again just to check USB with it.



Strangely, no one else has reported any tests with Pinebook Pro and `2022-07` so far 😐

**Comment by Strit** [comment]
> I haven't checked for USB on the Pinebook Pro. After the integrated kb didn't work, I didn't proceed further with testing.

As far as I know, the keyboard in the PBP is on the USB bus. So if the keyboard does not work at all, then USB likely does not work.

**Comment by ItsHarper** [comment]
~~The keyboard communicates via I2C, not USB.~~

Sorry, just realized you weren't talking about the PP keyboard. I have no knowledge about the PBP keyboard.

**Comment by CameronNemo** [comment]
FYI: https://lists.denx.de/pipermail/u-boot/2022-July/489246.html

Several people have run into this issue, including me, but others have not. May be wise to revert that commit or test the PBP further. Not sure why people would see the issue on vanilla U-Boot but not Tow-Boot.

**Comment by samueldr** [comment]
Pinebook Pro, confirmed:

 - On-device keyboard not working
 - sysreset not working

These are likely to be platform specific issues (well, rk808 already tracked down), but I say so because the Pinebook (A64) doesn't have any problem with its USB keyboard.

* * *

Backported the rk8xx workaround

 - source: https://patchwork.ozlabs.org/project/uboot/patch/20220805113219.7316-1-msuchanek@suse.de/

And it **fixes both problems**. It also totally makes sense that power management issues can cause USB stuff to fail in some ways.

Thank you @CameronNemo, tracking down that issue first here helped.

**Comment by samueldr** [comment]
"Fixed" the boot order issues. A two-parter:

 - I had only implemented a change for allwinner, since changes upstream brought more trouble. I never actually applied the changes to the build.
 - I never ended-up forward porting the rockchip and amlogic boot order fixes.

This was easy.

**Comment by psstoyanov** [comment]
@samueldr , the latest one fails to build due to missing patch:

<details>

<summary> Log of build attempt </summary>

```zsh-shell
➜  ~  Tow-Boot git:(feature/u-boot-2022.07) ✗ ls
assets                default.nix        nixpkgs.nix  spi_installer.sha256sum
boards                doc                README.md    support
build_podman_pbp.log  embedded-linux-os  release.nix
COPYING               modules            result
inebookPro
Docker not installed

Available container managers on your system:
1) podman
2) Quit
Select one of the options or quit: 1

Selected:
 podman

NixOS image is present

(Using existing volume)
 $ nix-build --cores 0 '<Tow-Boot/default.nix>' -A pine64-pinebookPro
trace: Using default Nixpkgs revision '1905f5f2e55e0db0bb6244cfe62cb6c0dbda391d'...
trace: *****************************************
trace: * Evaluating device: pine64-pinebookPro *
trace: *****************************************
trace: Building with crossSystem?: aarch64-linux != aarch64-linux → we're not.
error: getting status of '/Tow-Boot/support/u-boot/2022.07/patches/0001-Revert-rockchip-Fix-MMC-boot-order.patch': No such file or directory
(use '--show-trace' to show detailed location information)
➜  ~ Tow-Boot git:(feature/u-boot-2022.07) ✗ git status
On branch feature/u-boot-2022.07
Your branch is up to date with 'origin/feature/u-boot-2022.07'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   support/docker/build.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        build_podman_pbp.log
        spi_installer.sha256sum

no changes added to commit (use "git add" and/or "git commit -a")
➜  ~  Tow-Boot git:(feature/u-boot-2022.07) ✗ git log --format=short
commit 96c19c79e084f2e80293dce8cd3cdf9ce8beb3ee (HEAD -> feature/u-boot-2022.07, origin/feature/u-boot-2022.07)
Author: Samuel Dionne-Riel <samuel@dionne-riel.com>

    odroid-C2: use Tow-Boot armTrustedFirmwareTools
```

</details>

I had to manually copy over the patch in question from 2021.10 dir: https://github.com/Tow-Boot/Tow-Boot/blob/released/support/u-boot/2021.10/patches/0001-Revert-rockchip-Fix-MMC-boot-order.patch

**Comment by psstoyanov** [comment]
Confirmed the previous finding with PBP (keyboard not working) as resolved :+1: 

Will check RP64 in a bit.

**Update:**
Works fine with RP64 :+1:

**Comment by psstoyanov** [comment]
Alright, I can see that there is a change in the initial comment there with a task list.

Will check with RP64/ PBP and PP against https://github.com/Tow-Boot/Tow-Boot/pull/178/commits/e02d101b0951f7ffad7ec8fe4f3d09996b0b4e34 in the evening and tomorrow.

**Comment by psstoyanov** [comment]
@samueldr , result with RP64 from blank SPI against dbbbf5a :

- [x] USB keyboard works as expected both during installation and booting cycle  
- [x] Booting my eMMC Manjaro image as expected 
- [x] Booting LibreElec image from SD card as expected 

RP64 `spi.installer.img` sha256sum: `ce67a17e9671ce50e4bb14d3fd11a8c5db5564f7415d70070c2a296d78369d01`

Note:
I'm not sure what's the preferred boot order. 
On RP64 it preferred the eMMC over the SD card which appears to be the expected behaviour.

**Comment by samueldr** [comment]
> Note:
> I'm not sure what's the preferred boot order.
> On RP64 it preferred the eMMC over the SD card which appears to be the expected behaviour.

That's it, it works on a gradient, preferring "most internal to least internal", so e.g. eMMC, SD, USB... At least that's the expectation. Note that there might be some surprises with the current implementation, e.g. NVMe might happen after SD on some platforms. That would not be a regression. Regressions would only be if booting the operating system prefers SD to eMMC.

**Comment by psstoyanov** [comment]
Just checked with pinephoneA64 against https://github.com/Tow-Boot/Tow-Boot/commit/dbbbf5aaeee96e42dcc62299ff5cd4f6e3a28408.

Worked as expected on the A64 PinePhone:
- [x] Default boot from MMC
- [x] Boot from SD using Vol Down
- [x] Use jumpdrive via Vol Up

Helpful tool if the SD has uboot: [bootinfo](https://git.sr.ht/~martijnbraam/bootinfo)
Will post the shasum tomorrow of the mmc installer image.

**Comment by bgkillas** [comment]
would it be possible to skip 2022.07 and go to 2022.10 ? there have been some more improvements in regards to the pinephone pro that seem nice

**Comment by PureTryOut** [comment]
Sure, but that would mean all testing has basically beem for nothing. This has been open for quite a while already, I'd prefer it if we can just get this through, stop delaying this any longer, and then work on the next version.

**Comment by samueldr** [comment]
This PR will merge as-is, I will likely also cut a release with 2022.07 (and another trivial~ish change set), and then handle 2022.10 ASAP.

Sorry, I've been tied-up with $WORK :/.

**Comment by samueldr** [comment]
:x:  `radxa-zero2` seems broken ~~(Card did not respond to voltage select!: -110)~~

This is not a supported board by upstream, so this is not entirely unexpected in some ways.

More details: mmc numbering unexpectedly changed. This caused other issues with the installer and accidentally blew-up the installed OS.

**Comment by neofeo** [comment]
@samueldr please give me something to flash on my rockpro64 spi or make a prerelease, mine is bricked with latest release. no keyboard, no nothing pal. i dont have the right uart cable to erase it manually.

**Comment by samueldr** [comment]
**[Force-push](https://github.com/Tow-Boot/Tow-Boot/compare/dbbbf5aaeee96e42dcc62299ff5cd4f6e3a28408..01561f00a591f1d5ddf92f8aca65e331d0ddffb6) details**

 - Cleaned-up history
 - Fixed eMMC naming on amlogic
 - Fixed boot order on amlogic
 - Made erase scripts handle failure better
 - Fixed radxa-zero2 mmc boot index due to oversight in initial port (see main PR description)
 - Fixed libreComputer-rocRk3399Pc USB (and other related changes from upstream)
 - Fixed libreComputer-amlS805xAc eMMC naming now that amlogic naming is changed and fixed

**Comment by samueldr** [comment]
*@shvetsnikita wrote:*

> `roc-rk3399-pc` USB doesn't work at all now (there is no such issue with Tow-Boot 2021.10-005) and #183 is still reproducible.

I don't know for #183, I'll have to look into it, but at the very least I have added fixes that should now fix USB with the 2022.07 upgrade.

**Comment by samueldr** [comment]
I didn't think initially I would need to test all devices to merge, and almost merged earlier without deeper testing, but I'm glad I waited.

I ended-up finding issues that were hardware-specific. I would have had to deal with them anyway after the upgrade otherwise.

I am unable to test the Rock Pi 4 family of devices at the moment. I'll have to try and rope a tester in before cutting the actual release. There were changes affecting RK3399 systems and I haven't even looked at how likely or unlikely it is that they will have some breakage.

I'll merge within 24 hours.

**Comment by shvetsnikita** [comment]
> I have added fixes that should now fix USB with the 2022.07 upgrade.

Just tested "feature/u-boot-2022.07" and "development" branches. On both branches USB Type-A ports works now (I didn't tested Type-C ports yet) although both throw USB-related errors in both cases, even if no USB devices is attached ("Failed to get clocks"). However, there is severe regression on development branch (I flashed it to SPI) - right after "Please press ... to enter the boot menu." Tow-Boot starting to scan mmc, print stack trace and then reboot. I can get into the menu if I press Esc soon enough, but even if I choice USB I still getting same outcome. Yet somehow spiinstaller works fine, I seeing issue only when I have Tow-Boot installed in SPI (shared image was not tested).

**Comment by samueldr** [comment]
Moving to #209.

**Pull request merged**
