### PR TITLE
Tow-Boot: update U-Boot to 2021.10

### PR DESCRIPTION
**Pull request by samueldr**
**This still needs some testing**.

* * *

(Original description)

Only one target platform was tested, and not entirely so.

All boards built though.

I am only opening this to "show my work", and hopefully help any potential users wanting to get their hands dirty with the newer U-Boot release.

I will look in taking some time to test this correctly on all the major SoC families soon enough™ to cut the next release with only this upgrade.

* * *

### TODO

 * [x] check if poweroff now works on RK3399
 * [x] Check ^C behaviour at boot
 * [x] Add workaround for eMMC and rk3399 (see PPP PR)

 - [x] Test on hardware

### CODE REVIEW

**Comment by samueldr** [comment]
:x: a NixOS system using `extlinux.conf` based boot does not boot with this branch. 

Hangs at:

```
Moving Image from 0x2080000 to 0x2200000, end=4cf0000                                                                                                          
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
```

Same exact system boots fine on `002`. I see some bisecting action in my close future...

**Comment by kentdobias** [comment]
My Pinebook Pro with Tow-Boot on the SPI boots smoothly with this branch using EFI based boot via systemd-boot.

**Comment by samueldr** [comment]
:x: Breaking out of the boot does not go to the menu.

It might be that a patch to handle ^C has gone wrong.

**EDIT**: confirmed, only using escape does go to the menu, must be ^C custom handling not being forward ported appropriately.

**Comment by samueldr** [comment]
This latest update fixes the issue with the menu not being shown when breaking using ^C or even Escape depending on the context (USB keyboard vs. serial console).

This also rebases on the current state of `development`.

**Comment by samueldr** [comment]
@CRTified I may need you to test the `radxa-RockPi4C` changes, as I had to edit a patch.

It builds, and the change seems correct at a glance.

**Comment by samueldr** [comment]
@L-as one of the patches for the ODROID N2 was dropped, but the exact same was mainlined, so I'm not considering this *itself* an issue needing to be tested.

Though obviously, if you can spare the time to test, that would be nice.

**Comment by samueldr** [comment]
# TODO

Some issues with eMMC and RK3399:

 - [x] https://patchwork.ozlabs.org/project/uboot/patch/20211101044347.17822-1-yifeng.zhao@rock-chips.com/

**Comment by CRTified** [comment]
Regarding the rockPi4C:
Installer fails with
```
 ********* 
 * ERROR * 
 ********* 

This is the installer for: [radxa-rockPi4C]
The board detected is:     [radxa-RockPi4C]
```

Going to try this patch now:
```diff
diff --git a/boards/radxa/default.nix b/boards/radxa/default.nix
index 7331561..cff959d 100644
--- a/boards/radxa/default.nix
+++ b/boards/radxa/default.nix
@@ -2,7 +2,7 @@
 
 {
   radxa-RockPi4C = rockchipRK399 {
-    boardIdentifier = "radxa-rockPi4C";
+    boardIdentifier = "radxa-RockPi4C";
     defconfig = "rock-pi-4c-rk3399_defconfig";
     SPISize = 4 * 1024 * 1024; # 4 MiB
     patches = [
```

**Comment by CRTified** [comment]
That patch fixes the installer:
```
5002 bytes read in 4 ms (1.2 MiB/s)
## Executing script at 00500000


Firmware installer


devtype = usb
devnum = 0
bootpart = 2

:: Starting flash operation

-> Initializing SPI Flash subsystem...
SF: Detected XT25F32B with page size 256 Bytes, erase size 4 KiB, total 4 MiB

-> Reading Flash content...
device 0 whole chip
SF: 4194304 bytes @ 0x0 Read: OK

-> Reading new firmware from storage...
1566088 bytes read in 97 ms (15.4 MiB/s)

[...]

✅ Flashing seems to have been successful!

Press any key to reboot...
resetting ...

U-Boot TPL 2021.10 (Oct 04 2021 - 15:09:26)
[...]
```

Sorry that I only got time to do it now.

**Comment by samueldr** [comment]
Tested:

 - ✔️ libreComputer-amlS805xAc
 - ✔️ libreComputer-rocRk3399PcMezzanine
 - ✔️ orangePi-pc
 - ✔️ orangePi-zeroPlus2H5
 - ✔️ pine64-pineA64LTS
 - ✔️ pine64-pinebookA64
 - ✔️ pine64-pinebookPro
 - ✔️ raspberryPi-aarch64
 - ✅ radxa-RockPi4C
 - 🟦 olimex-teresI
 - 🟦 pine64-pineA64
 - 🟦 pine64-rockpro64
 - ❔ odroid-C2
 - ❔ odroid-N2

> ✔️ are tested locally by me  
> ✅ are reported by community members  
> 🟦 are untested but likely good due to similarity to other boards  
> ❔ are unknown, assumed as good as upstream U-Boot

**Pull request merged**
