### PR TITLE
boards: Add olimex-teresI

### PR DESCRIPTION
**Pull request by samueldr**
*I do not own this board, it will need a tester before this is merged.*

### CODE REVIEW

**Comment by Thra11** [comment]
I created an SD card with the Tow-Boot disk-image, followed by two more partitions, a 20M firmware partition (empty except for a single file, `config.txt`), and a bootable system partition containing a nixos system (These two partitions are copied from another SD card with a working system using u-boot). The internal eMMC does not currently have any bootloaders or bootable partitions on it.

If I fit this SD card, power on the system, and leave it alone, it boots just fine.

If I interrupt it by pressing Ctrl+C when prompted, it shows the menu, which is navigable using the keyboard. However, all of the "Boot from *" options fail, even "Boot from SD", despite there being a (clearly) bootable SD card fitted. Will continue to investigate...

**Comment by samueldr** [comment]
~~A fresh build from the current tip of `development` or using that first release? It's possible [cancelling boot with ^C is cancelling the commands list](https://github.com/Tow-Boot/Tow-Boot/commit/5ec6abbe8c85758084d27d0a5c3179e08d52a978) if you used the first release.~~ DUH... It's a build from this PR... disregard this.

Note that the "firmware partition" you're adding is useless; in the NixOS generic sd image, that "FIRMWARE" partition is the IBF (Initial Boot Firmware, read: U-Boot) exclusively used for the Raspberry Pi family of hardware.

Is that "bootable system partition" partition marked as *bootable*? Starting from the `disk-image.img` file it would be GPT. See #25 for some notes about setting a GPT partition as "bootable".

I guess I could test on any of my A64 targets for this. It wouldn't surprise me if the *Boot from __* options are failing due to some weirdness, impurities and environmental pollution. I might have seen a similar issue previously while trying to boot some targets.

**Review by Thra11 — APPROVED** [review]
Have logged the problems with the menu as #29, which seems unlikely to be specific to this board, so looks good to me.

**Comment by Thra11** [comment]
> Is that "bootable system partition" partition marked as _bootable_?

Yes. I added a legacy bootable flag in fdisk.

> Note that the "firmware partition" you're adding is useless.

I believe you're probably right. In theory the `config.txt` is supposed to be read to set `debug=on`, in order to enable/disable the headphone jack serial output (It doesn't have a physical switch like the pinebook-pro and pinephone). It's unlikely to be doing anything at the moment, just lying around on a random partition.

**Pull request merged**
