### PR TITLE
Configure GitHub Actions for building images

### PR DESCRIPTION
**Pull request by jirutka**
- Automatically build images for each device on push and on pull requests.
- Upload the built images to the workflow Artifacts.
- Upload the built archives to the Release if building a release tag.

Please note that I have little to no experience with nix. This workflow works, but the prepare-cache job is quite slow (see the TODO note) and the cache (saved /nix/store) is really big.

Demo: https://github.com/jirutka/Tow-Boot/actions/runs/3177942851

The following Actions need to be enabled in the repo: `actions/upload-artifact@v3`, `actions/download-artifact@v3`, and `softprops/action-gh-release@v1`.

### CODE REVIEW

**Comment by Strit** [comment]
I think this is a great addition. It would make it really easy for people not familiar with nix, to still test a PR's builds.

**Comment by jirutka** [comment]
@samueldr gentle ping

**Comment by samueldr** [comment]
Hi, sorry for the delay.

I hate piling on apologies, but this might end-up not being needed.

I have lined-up something to finish looking into, where we would have a [*Hydra*](https://github.com/NixOS/hydra) instance handling CD and CI. By the nature of how it works, and how Tow-Boot is setup, it will be better suited.

Note that yes, I agree, having the PRs built is needed and will be helpful.

**Comment by samueldr** [comment]
Hi, sorry it took some time until I could get around back to this.

Somewhat related to that, announced in the Tow-Boot matrix room, if that helps understand some of the situation, and how I'm moving forward to prevent such a situation to happen again.

 - https://gist.github.com/samueldr/8750e4aabbc23badec7a8798cabd4ed1

* * *

So, the Hydra infra project that could have been used (from a third party to all of us) is on the ice, in the end, so we'll be using GHA waiting for it to be thawed back.

I'll evaluate your changes, determine whether or not there are changes to be made, but will most likely at least keep attribution for the majority of it. I'll be looking into it once the current release is out, since it's already getting a bit long in the tooth, and *should* be basically ready.

**Comment by samueldr** [comment]
WIP additions here:

 - https://github.com/samueldr/Tow-Boot/tree/feature/github-actions

Alright, so I've looked into it, and added two main things (other than trivial "cleanups"):

  - Relies on the new [magic-nix-cache](https://github.com/DeterminateSystems/magic-nix-cache) action
  - Updated `uses` to those now used by docs
  - Generates the matrix dynamically, meaning that new devices are automatically accounted for

Still TODO:

 - Configure with `-CI` release suffix
 - Add `docs` build to the CI so changes to docs are at least shown to build.
 - Test the releases thing works as expected on my personal repo

Later, once #238 is in, we'll remove the *cheaty* thing removing the source tarballs. Since the actually-in-use tree will be easier to point people at. I already removed its removal of config and binaries, since they are useful:

 - the binaries can be used to manually update the partition one one's device
 - the config file is quite small, and shows the in-use full config, allowing one to guesstimate at some issues down the line

**Comment by samueldr** [comment]
:laughing: Nix won't stand for your *shenanigans*

 - https://github.com/samueldr/Tow-Boot/actions/runs/5480849318/jobs/9984489954#step:5:58

I was curious why it was rebuilding, turns out that yes, cheating is naughty!

**Comment by samueldr** [comment]
Thank you @jirutka, your contributions really helped me hit the ground running, and deal only with details work.

I'll be cleaning up my work tomorrow, and pushing this here. It still broadly relies on a lot of what you did.

**Comment by samueldr** [comment]
With this push:

  - I rebased on current `development`
  - Made the devices matrix dynamic
  - Added docs to the build
  - Some misc. cleanups
  - Simplified some bits
      - Used a new pre-made nix caching action
      - Removed source from built archive

I also configured the org to allow the selected action origins

The original commit is unchanged [other than a rebase].

**Pull request merged**
