### PR TITLE
Add support for OrangePi PC2

### PR DESCRIPTION
**Pull request by ghost**
OrangePi PC2 is a SBC based on Allwinner H5 chipset.
It is supported in crust-firmware and in many aspects identical to orangePi-zeroPlus2H5.

Verified that the following functionality works:
- Tow-Boot is installed with shared-storage scheme on the SD card.
- HDMI output and USB keyboard input
- Serial console input and output using a CP2102 USB to UART dongle
- Extlinux boot off USB devices of official NixOS 22.11 kernel 5.15 SD images and Armbian kernel 6.xx SD images.
- Uefi boot of NixOS hangs when the system fails to find root device by filesystem label `NIXOS_SD` in Stage1 initrd.  
- Uefi GRUB however works both in UART console and on a 4K screen at native resolution with HDMI.
- Currently only Armbian can boot to desktop, while with NixOS image the video output is cut off immediately when leaving GRUB, likely because of [missing graphics drivers](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/staging/media/sunxi/cedrus).  (kernel configuration option ``CONFIG_VIDEO_SUNXI_CEDRUS`` is enabled on Armbian but not NixOS).

### CODE REVIEW

**Comment by ghost** [comment]
Untested: Booting an OS from SD (assumed working).  Ethernet (assumed working).

This device does not have SPI flash or onboard storage.

**Comment by ghost** [comment]
> Uefi boot of NixOS hangs when the system fails to find root device by filesystem label NIXOS_SD in Stage1 initrd.
Update: I am happy to report that latest NixOS stable, [UEFI ISO image](https://channels.nixos.org/nixos-22.11/latest-nixos-gnome-aarch64-linux.iso), boots normally on this device.

There is still no graphical output post-GRUB.  Any suggestions?

**Comment by samueldr** [comment]
Hi! :wave: thanks for the contribution, and sorry it took a while until I got around to it.

Since it looks like it's a *trivial allwinner board*, I suspect this is 100% sufficient, and will go in basically as-is, once confirmed on my end that it does build.

It's likely that the issues you're seeing appear after GRUB are maybe unrelated to what Tow-Boot does. Checking with the equivalent U-Boot release would help, but first testing against the development branch since it's on 2022.07 would have also been a way to see if for some reason it was Tow-Boot. Though there is still one possibility it's a U-Boot × Linux problem, where the DT in the source tree needs to be synced with mainline Linux's for that board.

* * *

### Things to do (trivial, I'll be doing them)

 - [x] Change target branch to development
 - [x] Rebase if needed (unlikely)
 - [x] Verify it still builds

As far as testing I won't be able to, but given it's Allwinner H5, I have good confidence that it will *just work*, barring the same flavour of DT updates needed.


(Marking draft so I don't forget to handle these bits.)

**Comment by samueldr** [comment]
Hi, sorry it took a while to handle.

I did the rebase, no conflicts.

If you can take a look now that it's been rebased against 2023.07, it would be really useful, since I don't have the hardware to test against.

Though, allwinner devices *generally* end-up *just working* in U-Boot, as long as other from the same overall vintage are. So I will merge anyway before 2023.07-007 is released.

**Comment by samueldr** [comment]
(No one saw anything... :eyes:)

**Comment by ghost** [comment]
Hello.  Sorry but I also do not have the device to test against anymore.
You can close the PR now.

**Comment by samueldr** [comment]
No worries, since this is running against Allwinner hardware, it's generally expected to *just work*, with U-Boot, as long as other equivalent Allwinner devices are. So it will be merged.

And thank you for the contribution, still!

**Pull request merged**
